# Generated by Django 2.0.1 on 2018-01-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
    ]
