# Generated by Django 2.0.1 on 2018-01-08 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20180108_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='slug',
        ),
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True, verbose_name='file name'),
        ),
    ]
